In [7]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
wine=load_wine()
wine_data=wine.data
wine_target=wine.target
df_data=pd.DataFrame(data=wine_data,columns=wine.feature_names)
df_labels=pd.DataFrame(data=wine_target,columns=["kinds"])
import seaborn as sns
data = pd.concat([df_data, df_labels], axis=1)

In [8]:
data

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,kinds
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [11]:
X=data.iloc[:,0:13].values
y=data.iloc[:,13].values
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)

Y=pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.2,random_state=0)

In [12]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(10,input_shape=(4,),activation='tanh'))
model.add(Dense(8,activation='tanh'))
model.add(Dense(6,activation='tanh'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 10)                50

 dense_17 (Dense)            (None, 8)                 88

 dense_18 (Dense)            (None, 6)                 54

 dense_19 (Dense)            (None, 3)                 21

=================================================================
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________

In [14]:
#Defining the model 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD,Adam
from keras.layers import Input, Dense
from keras.models import Model

# 이는 텐서를 반환합니다
inputs = Input(shape=(13,))
x = Dense(10, activation='relu')(inputs)
x2 = Dense(8, activation='relu')(x)
x3 = Dense(6, activation='relu')(x2)
output=Dense(2,activation='softmax')(x3)

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 10)                50

 dense_17 (Dense)            (None, 8)                 88

 dense_18 (Dense)            (None, 6)                 54

 dense_19 (Dense)            (None, 3)                 21

=================================================================
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________

In [15]:
import tensorflow as tf

X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [16]:
model.fit(X_train, y_train, epochs=100, verbose=0)

In [17]:
test_mse_score, test_mae_score = model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 5ms/step - loss: 2.7215

TypeError: cannot unpack non-iterable float object